services:
  AndreasWolf\Migrations\Service\DoctrineService:
    arguments:
      - '@TYPO3\CMS\Core\Package\PackageManager'
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - '@TYPO3\CMS\Core\Log\LogManager'

  AndreasWolf\Migrations\Command\DiffCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:diff'
        schedulable: false
  AndreasWolf\Migrations\Command\GenerateCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:GenerateCommand'
        schedulable: false

  AndreasWolf\Migrations\Command\ExecuteCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:execute'
        schedulable: false
  AndreasWolf\Migrations\Command\MigrateCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:migrate'
        schedulable: false
  AndreasWolf\Migrations\Command\RollupCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:rollup'
        schedulable: false
  AndreasWolf\Migrations\Command\UpToDateCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:uptodate'
        schedulable: false
  AndreasWolf\Migrations\Command\StatusCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:status'
        schedulable: false
  AndreasWolf\Migrations\Command\VersionCommand:
    arguments:
      - '@AndreasWolf\Migrations\Service\DoctrineService'
    tags:
      - name: 'console.command'
        command: 'migrations:version'
        schedulable: false
